name: Update Vendor Hash
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Install nix-update
        run: nix profile install nixpkgs#nix-update
      - name: Update vendor hash
        run: |
          nix-update --flake --version=skip default
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: '[CI] update nix'
          file_pattern: 'flake.nix flake.lock'